"""initial_schema

Revision ID: fd359cf82c62
Revises:
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fd359cf82c62'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anonymous_players',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('source_manifest', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_index(op.f('ix_dataset_versions_category'), 'dataset_versions', ['category'], unique=False)
    op.create_index(op.f('ix_dataset_versions_is_active'), 'dataset_versions', ['is_active'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'code')
    )
    op.create_index(op.f('ix_entities_category'), 'entities', ['category'], unique=False)
    op.create_table('country_values',
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('area_km2', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gdp_per_capita_usd', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('temp_c', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('capital', sa.String(length=160), nullable=False),
    sa.Column('capital_lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('capital_lon', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('dataset_id', 'entity_id')
    )
    op.create_table('puzzles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('day', sa.Date(), nullable=True),
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'day')
    )
    op.create_table('rounds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('puzzle_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['anonymous_players.id'], ),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'puzzle_id')
    )
    op.create_index(op.f('ix_rounds_player_id'), 'rounds', ['player_id'], unique=False)
    op.create_index(op.f('ix_rounds_puzzle_id'), 'rounds', ['puzzle_id'], unique=False)
    op.create_table('guesses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('round_id', sa.String(length=36), nullable=False),
    sa.Column('turn', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('feedback', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'entity_id'),
    sa.UniqueConstraint('round_id', 'idempotency_key'),
    sa.UniqueConstraint('round_id', 'turn')
    )
    op.create_index(op.f('ix_guesses_round_id'), 'guesses', ['round_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guesses_round_id'), table_name='guesses')
    op.drop_table('guesses')
    op.drop_index(op.f('ix_rounds_puzzle_id'), table_name='rounds')
    op.drop_index(op.f('ix_rounds_player_id'), table_name='rounds')
    op.drop_table('rounds')
    op.drop_table('puzzles')
    op.drop_table('country_values')
    op.drop_index(op.f('ix_entities_category'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_dataset_versions_is_active'), table_name='dataset_versions')
    op.drop_index(op.f('ix_dataset_versions_category'), table_name='dataset_versions')
    op.drop_table('dataset_versions')
    op.drop_table('anonymous_players')
    # ### end Alembic commands ###
